sudo: required
language: bash
env:
  global:
  - IMAGE_NAME=gableroux/unity3d:2018.2.6f1
  - BUILD_NAME=ExampleProjectName
services:
- docker
before_install:
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: test
    script: "chmod +x ./ci/docker_test.sh && ./ci/docker_test.sh"
    env: TEST_PLATFORM=playmode
    addons:
      artifacts:
        target_paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=Android
    script: "chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh"
    addons:
      artifacts:
        target_paths:
        - "./Builds/"
